2018 MASSACRE
```{r}
modelData
pre2018 <- modelData %>% filter(year < 2018) 
pre2018 <- pre2018 %>% select(-c(Name, year, team)) %>%  filter(!position %in% c("ST", "K"))
preds2018 <- modelData %>% filter(year == 2018) %>% filter(!position %in% c("ST", "K"))
copy <- preds2018
preds2018 <- preds2018 %>% select(-c(Name, year, team))

yTrain <- pre2018$actualPoints
xTrain <- pre2018 %>% select(c(-actualPoints)) %>% 
  select(everything()) %>%  data.matrix()
yTest <- preds2018$actualPoints
xTest <- preds2018 %>% select(c(-actualPoints)) %>% 
  select(everything()) %>%  data.matrix()

trainPLS <- pre2018 %>% 
  group_by(position, yearsFromPresent) %>% 
  summarise(avgPositionPTs = mean(PPR)) %>% 
  ungroup() %>% 
  right_join(pre2018) %>% 
  mutate(position = avgPositionPTs) %>% 
  select(-avgPositionPTs, -yearsFromPresent, -closestName)
trainPLS <- pre2018 %>% 
  group_by(depthChart, yearsFromPresent) %>% 
  summarise(avgDepthChartPTs = mean(DKPt)) %>% 
  ungroup() %>% 
  right_join(trainPLS) %>% 
  mutate(depthChart = avgDepthChartPTs) %>% 
  select(-avgDepthChartPTs)

testPLS <- preds2018 %>% 
  group_by(position, yearsFromPresent) %>% 
  summarise(avgPositionPTs = mean(PPR)) %>% 
  ungroup() %>% 
  right_join(preds2018) %>% 
  mutate(position = avgPositionPTs) %>% 
  select(-avgPositionPTs, -yearsFromPresent, -closestName)
testPLS <- preds2018 %>% 
  group_by(depthChart, yearsFromPresent) %>% 
  summarise(avgDepthChartPTs = mean(DKPt)) %>% 
  ungroup() %>% 
  right_join(testPLS) %>% 
  mutate(depthChart = avgDepthChartPTs) %>% 
  select(-avgDepthChartPTs)
```

#Calculate differences
```{r}
logit2018 <- lm(actualPoints ~., data = pre2018, na.action = na.exclude)
rf2018 <- randomForest(actualPoints~., data = pre2018)
predictions <- predict(logit2018,preds2018[,-1], type="response")
predictionsrf <- predict(rf2018,preds2018[,-1], type="response")
copy$predictions <- predictions
copy %>% arrange(-predictions)

copy

comparison <- copy %>% 
  arrange(position, -predictions) %>% 
  group_by(position) %>% 
  mutate(predictedPosRank = row_number()) %>% 
  ungroup() %>% 
  arrange(position, rank) %>% 
  group_by(position) %>% 
  mutate(espnPosRank = row_number()) %>% 
  ungroup() %>% 
  arrange(position, -actualPoints) %>% 
  group_by(position) %>% 
  mutate(actualPosRank = row_number()) %>% 
  ungroup() %>% 
  select(Name, actualPoints, predictions, rank, actualPosRank, predictedPosRank, espnPosRank)


espn <- lm(actualPoints ~ rank, data = pre2018)
ranks <- data_frame(rank = preds2018$rank)
mse <- (preds2018$actualPoints  - predict(espn, ranks))^2 
espnRMSE <- (sum(mse / nrow(preds2018)))^.5

mse <- (preds2018$actualPoints - predictions)^2
myRMSE <- (sum(mse / nrow(preds2018)))^.5

cor(preds2018$actualPoints, predictions)

logit2018improvement <- 1 - myRMSE / espnRMSE

mse <- (preds2018$actualPoints - predictionsrf)^2
myRMSE <- (sum(mse / nrow(preds2018)))^.5

rf2018improvement <- 1 - myRMSE / espnRMSE
```

2018 ridge
```{r}
cv_fit <- cv.glmnet(xTrain, yTrain, alpha = 0, lambda = lambdas)
plot(cv_fit)
opt_lambda <- cv_fit$lambda.min
fit <- cv_fit$glmnet.fit



y_predicted <- predict(fit, s = opt_lambda, newx = xTest)
sst <- sum((yTest - mean(yTest))^2)
sse <- sum((y_predicted - yTest)^2)

plot(y_predicted, yTest)

# R squared
rsq <- 1 - sse / sst
rsq

rmse <- (sse / length(yTest))^.5


ridge2018improvement <- 1 - rmse / espnRMSE

class(y_predicted)
copy$predictions <- as.numeric(y_predicted)
copy %>% arrange(-predictions)
```

2018 PLS 
```{r}
model <- train(
  actualPoints~., data = trainPLS, method = "pls",
  scale = TRUE,
  trControl = trainControl("cv", number = 10),
  tuneLength = 10
  ) 

plot(model) 
model$bestTune 
summary(model$finalModel) 

predictions <- model %>% predict(testPLS) 

MSE <- mean((predictions - testPLS$actualPoints)^2)
RMSE <- (sum(MSE))^.5

pls2018improvement <- 1 - RMSE / espnRMSE
```



2017
```{r}
pre2017 <- modelData %>% filter(year < 2017) 
pre2017 <- pre2017 %>% select(-c(Name, year, team)) %>%  filter(!position %in% c("ST", "K"))
preds2017 <- modelData %>% filter(year == 2017) %>% filter(!position %in% c("ST", "K"))
copy <- preds2017
preds2017 <- preds2017 %>% select(-c(Name, year, team))

yTrain <- pre2017$actualPoints
xTrain <- pre2017 %>% select(c(-actualPoints)) %>% 
  select(everything()) %>%  data.matrix()
yTest <- preds2017$actualPoints
xTest <- preds2017 %>% select(c(-actualPoints)) %>% 
  select(everything()) %>%  data.matrix()

trainPLS <- pre2017 %>% 
  group_by(position, yearsFromPresent) %>% 
  summarise(avgPositionPTs = mean(PPR)) %>% 
  ungroup() %>% 
  right_join(pre2017) %>% 
  mutate(position = avgPositionPTs) %>% 
  select(-avgPositionPTs, -yearsFromPresent, -closestName)
trainPLS <- pre2017 %>% 
  group_by(depthChart, yearsFromPresent) %>% 
  summarise(avgDepthChartPTs = mean(DKPt)) %>% 
  ungroup() %>% 
  right_join(trainPLS) %>% 
  mutate(depthChart = avgDepthChartPTs) %>% 
  select(-avgDepthChartPTs)

testPLS <- preds2017 %>% 
  group_by(position, yearsFromPresent) %>% 
  summarise(avgPositionPTs = mean(PPR)) %>% 
  ungroup() %>% 
  right_join(preds2017) %>% 
  mutate(position = avgPositionPTs) %>% 
  select(-avgPositionPTs, -yearsFromPresent, -closestName)
testPLS <- preds2017 %>% 
  group_by(depthChart, yearsFromPresent) %>% 
  summarise(avgDepthChartPTs = mean(DKPt)) %>% 
  ungroup() %>% 
  right_join(testPLS) %>% 
  mutate(depthChart = avgDepthChartPTs) %>% 
  select(-avgDepthChartPTs)
```


```{r}
logit2017 <- lm(actualPoints ~., data = pre2017)
rf2017 <- randomForest(actualPoints~., data = pre2017)
predictions <- predict(logit2017,preds2017[,-1], type="response")
predictionsrf <- predict(rf2017, preds2017[,-1], type = "response")
copy$predictions <- predictions
copy %>% arrange(-predictions)

comparison <- copy %>% 
  arrange(position, -predictions) %>% 
  group_by(position) %>% 
  mutate(predictedPosRank = row_number()) %>% 
  ungroup() %>% 
  arrange(position, rank) %>% 
  mutate(espnPosRank = row_number()) %>% 
  ungroup() %>% 
  arrange(position, -actualPoints) %>% 
  group_by(position) %>% 
  mutate(actualPosRank = row_number()) %>% 
  ungroup() %>% 
  select(Name, actualPosRank, predictedPosRank, espnPosRank)


espn <- lm(actualPoints ~ rank, data = pre2017)
ranks <- data_frame(rank = preds2017$rank)
mse <- (preds2017$actualPoints  - predict(espn, ranks))^2 
espnRMSE <- (sum(mse / nrow(preds2017)))^.5


mse <- (preds2018$actualPoints - predictions)^2
myRMSE <- (sum(mse / nrow(preds2018)))^.5

logit2017improvement <- 1 - myRMSE / espnRMSE

mse <- (preds2018$actualPoints - predictionsrf)^2
myRMSE <- (sum(mse / nrow(preds2018)))^.5

rf2017improvement <- 1 - myRMSE / espnRMSE
```

2017 ridge
```{r}
cv_fit <- cv.glmnet(xTrain, yTrain, alpha = 0, lambda = lambdas)
plot(cv_fit)
opt_lambda <- cv_fit$lambda.min
fit <- cv_fit$glmnet.fit



y_predicted <- predict(fit, s = opt_lambda, newx = xTest)
sst <- sum((yTest - mean(yTest))^2)
sse <- sum((y_predicted - yTest)^2)

plot(y_predicted, yTest)

# R squared
rsq <- 1 - sse / sst
rsq

rmse <- (sse / length(yTest))^.5


ridge2017improvement <- 1 - rmse / espnRMSE

class(y_predicted)
copy$predictions <- as.numeric(y_predicted)
copy %>% arrange(-predictions)
```

PLS
```{r}
model <- train(
  actualPoints~., data = trainPLS, method = "pls",
  scale = TRUE,
  trControl = trainControl("cv", number = 10),
  tuneLength = 10
  ) 

plot(model) 
model$bestTune 
summary(model$finalModel) 

predictions <- model %>% predict(testPLS) 

MSE <- mean((predictions - testPLS$actualPoints)^2)
RMSE <- (sum(MSE))^.5

pls2017improvement <- 1 - RMSE / espnRMSE
```



2016
```{r}
pre2016 <- modelData %>% filter(year < 2016) 
pre2016 <- pre2016 %>% select(-c(Name, year, team)) %>%  filter(!position %in% c("ST", "K"))
preds2016 <- modelData %>% filter(year == 2016) %>% filter(!position %in% c("ST", "K"))
copy <- preds2016
preds2016 <- preds2016 %>% select(-c(Name, year, team))

yTrain <- pre2016$actualPoints
xTrain <- pre2016 %>% select(c(-actualPoints)) %>% 
  select(everything()) %>%  data.matrix()
yTest <- preds2016$actualPoints
xTest <- preds2016 %>% select(c(-actualPoints)) %>% 
  select(everything()) %>%  data.matrix()

trainPLS <- pre2016 %>% 
  group_by(position, yearsFromPresent) %>% 
  summarise(avgPositionPTs = mean(PPR)) %>% 
  ungroup() %>% 
  right_join(pre2016) %>% 
  mutate(position = avgPositionPTs) %>% 
  select(-avgPositionPTs, -yearsFromPresent, -closestName)
trainPLS <- pre2016 %>% 
  group_by(depthChart, yearsFromPresent) %>% 
  summarise(avgDepthChartPTs = mean(DKPt)) %>% 
  ungroup() %>% 
  right_join(trainPLS) %>% 
  mutate(depthChart = avgDepthChartPTs) %>% 
  select(-avgDepthChartPTs)

testPLS <- preds2016 %>% 
  group_by(position, yearsFromPresent) %>% 
  summarise(avgPositionPTs = mean(PPR)) %>% 
  ungroup() %>% 
  right_join(preds2016) %>% 
  mutate(position = avgPositionPTs) %>% 
  select(-avgPositionPTs, -yearsFromPresent, -closestName)
testPLS <- preds2016 %>% 
  group_by(depthChart, yearsFromPresent) %>% 
  summarise(avgDepthChartPTs = mean(DKPt)) %>% 
  ungroup() %>% 
  right_join(testPLS) %>% 
  mutate(depthChart = avgDepthChartPTs) %>% 
  select(-avgDepthChartPTs)

```



```{r}
logit2016 <- lm(actualPoints ~., data = pre2016)
predictions <- predict(logit2016,preds2016[,-1], type="response")
rf2016 <- randomForest(actualPoints ~., data = pre2016)
predictionsrf <- predict(rf2016,preds2016[,-1], type="response")

copy$predictions <- predictions
copy %>% arrange(-predictions)

comparison <- copy %>% 
  arrange(position, -predictions) %>% 
  group_by(position) %>% 
  mutate(predictedPosRank = row_number()) %>% 
  ungroup() %>% 
  arrange(position, rank) %>% 
  mutate(espnPosRank = row_number()) %>% 
  ungroup() %>% 
  arrange(position, -actualPoints) %>% 
  group_by(position) %>% 
  mutate(actualPosRank = row_number()) %>% 
  ungroup() %>% 
  select(Name, actualPosRank, predictedPosRank, espnPosRank)


espn <- lm(actualPoints ~ rank, data = pre2016)
ranks <- data_frame(rank = pre2016$rank)
mse <- (pre2016$actualPoints  - predict(espn, ranks))^2 
espnRMSE <- (sum(mse / nrow(pre2016)))^.5

mse <- (preds2018$actualPoints - predictions)^2
myRMSE <- (sum(mse / nrow(preds2018)))^.5

logit2016improvement <- 1 - myRMSE / espnRMSE

mse <- (preds2018$actualPoints - predictionsrf)^2
myRMSE <- (sum(mse / nrow(preds2018)))^.5

rf2016improvement <- 1 - myRMSE / espnRMSE

```

2016 ridge
```{r}
cv_fit <- cv.glmnet(xTrain, yTrain, alpha = 0, lambda = lambdas)
plot(cv_fit)
opt_lambda <- cv_fit$lambda.min
fit <- cv_fit$glmnet.fit



y_predicted <- predict(fit, s = opt_lambda, newx = xTest)
sst <- sum((yTest - mean(yTest))^2)
sse <- sum((y_predicted - yTest)^2)

plot(y_predicted, yTest)

# R squared
rsq <- 1 - sse / sst
rsq

rmse <- (sse / length(yTest))^.5


ridge2016improvement <- 1 - rmse / espnRMSE

class(y_predicted)
copy$predictions <- as.numeric(y_predicted)
copy %>% arrange(-predictions)
```


PLS 2016
```{r}
model <- train(
  actualPoints~., data = trainPLS, method = "pls",
  scale = TRUE,
  trControl = trainControl("cv", number = 10),
  tuneLength = 10
  ) 

plot(model) 
model$bestTune 
summary(model$finalModel) 

predictions <- model %>% predict(testPLS) 

MSE <- mean((predictions - testPLS$actualPoints)^2)
RMSE <- (sum(MSE))^.5

pls2016improvement <- 1 - RMSE / espnRMSE
```




combine all data
```{r}
df <- NULL
linears <- as.numeric(list(logit2018improvement, logit2017improvement, logit2016improvement))
rf <- as.numeric(list(rf2018improvement, rf2017improvement, rf2016improvement))
ridge <- as.numeric(list(ridge2018improvement, ridge2017improvement, ridge2016improvement))
pls <- as.numeric(list(pls2018improvement, pls2017improvement, pls2016improvement))

allModels <- as.data.frame(rbind(linears, rf, ridge, pls))
colnames(allModels) <- c("2018", "2017", "2016")

allModels

```

